### ISSUE TITLE
Travamento de Flood

### ISSUE THREAD

**Issue by andreemidio** [Grupo-OpenCV-BR/BenderBot#3]
É possivel criar uma blacklist do ultimo que mutou ou desmutou o Bender ?

Para evitar que o cara fique clicando nisso e fazendo ele ficar mandando mensagens atoa.

![image](https://user-images.githubusercontent.com/2787467/98025333-4c9e6800-1de8-11eb-9432-68c714305b8d.png)

**Comment by NataliaCarvalho03** [comment]
Oi, André! Acredito que é possível sim! Tem alguma dica do que poderia ser usado para resolver este problema? Inicialmente estou pensando em usar um arquivo json onde essa lista ficará armazenada, mas qualquer dica é bem vinda.

**Comment by andreemidio** [comment]
@NataliaCarvalho03 acho essa ideia boa e simples. O que acha @Willianjesusdasilva  ?

**Comment by Willianjesusdasilva** [comment]
é mole

**Comment by Willianjesusdasilva** [comment]
Eu faria o seguinte:
Gerar uma lista (pode ser até um arquivo txt)
onde tem uma lista de pessoas ordenadas por ID_pessoa;ID_pessoa;ID_pessoa
e se comportar em padrão de fila, sempre que inserir um novo numero, remover o primeiro

Exemplo:

Willian;Natalia;Andre

Insert_fila(Marcos)

Output: Natalia;Andre;Marcos

Assim, evitamos de um flood.

Só teremos flood se ouver um complo kkkkkkkkkkk

**Comment by NataliaCarvalho03** [comment]
Bueno, senhores, se estamos em acordo, irei atribuir esta tarefa a mim rsrs.
